name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Quality Checks Job
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check code formatting
        run: npm run format:check
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Type check
        run: npm run type-check
        
      - name: Build project
        run: npm run build

  # Testing Job
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Generate coverage report
        run: npm run test:coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  # Security Audit Job
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level=moderate
        
      - name: Check for known vulnerabilities
        run: npm audit --audit-level=high

  # Performance Check Job
  performance:
    name: Performance Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Check bundle size
        run: |
          echo "Checking bundle size..."
          if [ -d "dist" ]; then
            echo "Bundle size:"
            du -sh dist/*
          else
            echo "No dist directory found"
            exit 1
          fi

  # Browser Compatibility Job
  browser-tests:
    name: Browser Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start development server
        run: npm run dev &
        
      - name: Wait for server
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:3456 > /dev/null; do sleep 1; done'
        
      - name: Run browser tests
        run: |
          # Basic browser compatibility check
          echo "Testing browser compatibility..."
          curl -s http://localhost:3456 | grep -q "Gospel Game" || exit 1
          echo "Basic compatibility check passed"

  # Documentation Check Job
  docs:
    name: Documentation Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check documentation links
        run: |
          echo "Checking documentation files..."
          if [ ! -f "README.md" ]; then
            echo "README.md is missing"
            exit 1
          fi
          if [ ! -f "CONTRIBUTING.md" ]; then
            echo "CONTRIBUTING.md is missing"
            exit 1
          fi
          if [ ! -d "docs" ]; then
            echo "docs directory is missing"
            exit 1
          fi
          echo "Documentation check passed"

  # Final Status Check
  status:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [quality, test, security, performance, browser-tests, docs]
    
    steps:
      - name: Check all jobs completed
        run: |
          echo "All CI checks completed successfully!"
          echo "✅ Code Quality: Passed"
          echo "✅ Tests: Passed"
          echo "✅ Security: Passed"
          echo "✅ Performance: Passed"
          echo "✅ Browser Tests: Passed"
          echo "✅ Documentation: Passed" 