name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          echo "Verifying build output..."
          if [ ! -f "dist/index.html" ]; then
            echo "❌ dist/index.html not found"
            exit 1
          fi
          if [ ! -d "dist/assets" ]; then
            echo "❌ dist/assets directory not found"
            exit 1
          fi
          echo "✅ Build output verified"
          echo "📁 Files in dist/:"
          ls -la dist/
          echo "📁 Files in dist/assets/:"
          ls -la dist/assets/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages - ${{ github.sha }}'

      - name: Create deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Build Status:** Successful" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Tests:** All tests passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Bundle Size:** $(du -sh dist | cut -f1)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Deployed to:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> \
            $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Deployment Time:** $(date -u)" >> $GITHUB_STEP_SUMMARY

      - name: Verify deployment
        run: |
          echo "Waiting for deployment to be available..."
          sleep 30
          DEPLOY_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo "Checking deployment at: $DEPLOY_URL"
          if curl -s -f "$DEPLOY_URL" > /dev/null; then
            echo "✅ Deployment verified successfully"
          else
            echo "⚠️  Deployment may still be processing (this is normal)"
          fi
